### ISSUE TITLE
pivpn -a nopass and tcp/udp

### ISSUE THREAD

**Issue by samabsalom** [InnovativeInventor/docker-pivpn#7]
Hello! 
Great container thanks! 
It would be great if a feature could be added to allow nopass to be added in the setup.sh 

Also when i run the setup.sh it always makes 1194 tcp instead of udp. should it be doing that?

Thanks
Sam

**Comment by InnovativeInventor** [comment]
If you want to run commands within the docker container, type `docker exec -it container pivpn -a nopass`. Of course, switch container with either the container id or name (you can get this stuff by running `docker ps`)

It should default to UDP. This is what it looks like for me:

![screenshot-pivpn](https://user-images.githubusercontent.com/20117409/37879203-9ee75702-3042-11e8-888a-2e5d420414b8.png) Docker-pivpn uses PiVPN's script so it defaults to whatever they choose. 
This may be a problem on their side (try running it again, it may have been a brief mistake on their part).

I'll add a nopass option if I have time. It'll probably look somewhat like `setup.sh --nopass` 
Anyways, thanks for the feedback!

**Comment by samabsalom** [comment]
Hi thanks for adding the nopass option so quickly ! 

my pivpn correctly uses udp but its the container that publishes its port 1194 as tcp 

<img width="919" alt="screen shot 2018-03-26 at 09 50 33" src="https://user-images.githubusercontent.com/17027712/37896312-70842ed2-30db-11e8-9631-15879060b792.png">

ill keep looking. thanks !

Sam

**Comment by InnovativeInventor** [comment]
Hmmm. I've added two lines to the dockerfile to expose both 1194/udp and 1194/tcp, but it looks like its mapping to different ports. I might decide to do --network host instead to make things easier (it was like that originally), but I don't really have time until next weekend to work on this (maybe earlier if I'm lucky). Thanks for alerting me about this problem!
